export const TypeActions ={
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM:",
    REMOVE_CELL:"REMOVE_CELL",
    EDIT_CELL:"EDIT_CELL",
    SWITCH_CELL_EDIT:"SWITCH_CELL_EDIT",
    SORT_BY_MASK:"SORT_BY_MASK",
    ADD_CELL:"ADD_CELL",
    UPDATE_TITLES:"UPDATE_TITLES",
    ADD_DATA:"ADD_DATA",
    INPUT_LOG:"INPUT_LOG",
    UPDATE_LAST_ID:"UPDATE_LAST_ID",
    CLEAR_PRELOADER:"CLEAR_PRELOADER",
    OUTPUT_DATA:"OUTPUT_DATA"
}