export const TypeActions ={
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM:",
    REMOVE_CELL:"REMOVE_CELL",
    EDIT_CELL:"EDIT_CELL",
    SWITCH_CELL_EDIT:"SWITCH_CELL_EDIT",
    SORT_BY_MASK:"SORT_BY_MASK",
    ADD_CELL:"ADD_CELL",
    UPDATE_TITLES:"UPDATE_TITLES"
}